# Generated by Django 3.0.3 on 2020-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_work_hours',
            field=models.IntegerField(null=True),
        ),
    ]
