# Generated by Django 3.0.3 on 2020-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='loaded_work_hours',
            field=models.IntegerField(default=0),
        ),
    ]
