# Generated by Django 3.0.3 on 2020-02-27 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0004_issue_loaded_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='observer',
        ),
        migrations.AddField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(null=True, related_name='issues_watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
