# Generated by Django 3.0.3 on 2020-02-29 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0008_auto_20200229_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='issues_watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
