# Generated by Django 3.0.3 on 2020-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200229_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
