# Generated by Django 3.0.3 on 2020-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20200302_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
