# Generated by Django 3.0.3 on 2020-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20200306_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('OPEN', 'OPEN'), ('ASSIGNED', 'ASSIGNED'), ('CLOSED', 'CLOSED')], default='CREATED', max_length=50),
        ),
    ]
